image:
  fullnameOverride: norganas-kube-prune
  repository: norganas-kube-prune
  tag: #{Build.BuildId}#
  pullPolicy: IfNotPresent
  imagePullSecretName: <image-pull-secret>
imagePullSecrets: []
cronjob:
  schedule: #{scheduleQuery}#
  timeZone:	"America/Sao_Paulo"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

authorization: 
  serviceAccountName: <service-account-name>

configs:
  configMap: norganas-kube-prune
  path: /app/src/configs/configs.json
  subPath: configs.json

team: <team-label>
nodeSelector: {}
annotations: {}
tolerations: []
affinity: {}
secrets: {}
